export default function () {
  return {
    mascotas: [
      {
        id: '1crduv9a0dd',
        rutDue: '13113859-2',
        nombre: 'Sam',
        color: 'Negro',
        sexo: 'Macho',
        tipo: 'Perro',
        size: 'Mediano',
        edad: '9',
      },
      {
        id: 'c8pn0swtidw',
        rutDue: '21134910-8',
        nombre: 'Alba',
        color: 'Blanco',
        sexo: 'Hembra',
        tipo: 'Perro',
        size: 'Grande',
        edad: '12',
      },
      {
        id: '1f9u4dvnhpj',
        rutDue: '19234412-9',
        nombre: 'Pelusa',
        color: 'Blanca',
        sexo: 'Hembra',
        tipo: 'Gato',
        size: 'Grande',
        edad: '4',
      },
      {
        id: 'h0uvd1jlrz',
        rutDue: '19234412-9',
        nombre: 'Quira',
        color: 'Cafe Palido',
        sexo: 'Hembra',
        tipo: 'Perro',
        size: 'Mediano',
        edad: '2',
      },
      {
        id: 'bwg8xhuwvgo',
        rutDue: '21982232-9',
        nombre: 'Donatelo',
        color: 'Cafe',
        sexo: 'Macho',
        tipo: 'Tortuga',
        size: 'Pequeño',
        edad: '2',
      },
      {
        id: 'exd0gr2m9d',
        rutDue: '21982232-9',
        nombre: 'Nano',
        color: 'Negro',
        sexo: 'Macho',
        tipo: 'Perro',
        size: 'Grande',
        edad: '9',
      },
    ],

    validRut: false,
  }
}
